### ISSUE TITLE
Team description and project board.

### ISSUE THREAD

**Issue by gabrielyea** [gabrielyea/pokemon-capstone#21]
:star:  Our team has 2 persons. @D4nielJ  and @gabrielyea. :star: 

See our project [here](https://github.com/gabrielyea/pokemon-capstone/projects) :link:

**Comment by carlos-ssh** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
